/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BeginnerPortfolio {
  'id' : bigint,
  'title' : string,
  'tools' : Array<BeginnerPortfolioTool>,
  'about' : BeginnerPortfolioAbout,
  'projects' : Array<BeginnerPortfolioProject>,
  'hero' : BeginnerPortfolioHero,
  'contactCta' : BeginnerPortfolioContactCta,
  'introduction' : string,
  '_caseStudy' : [] | [BeginnerPortfolioCaseStudy],
  'certifications' : Array<BeginnerPortfolioCertification>,
  'skills' : Array<BeginnerPortfolioSkill>,
}
export interface BeginnerPortfolioAbout { 'bio' : string, 'focus' : string }
export interface BeginnerPortfolioCaseStudy {
  'title' : string,
  'research' : string,
  'strategy' : string,
  'learnings' : string,
  'execution' : string,
  'problem' : string,
}
export interface BeginnerPortfolioCertification {
  'url' : string,
  'title' : string,
}
export interface BeginnerPortfolioContactCta {
  'headline' : string,
  'contactUrl' : string,
  'ctaText' : string,
}
export interface BeginnerPortfolioHero {
  'headline' : string,
  'ctaViewWork' : string,
  'ctaContact' : string,
  'subheadline' : string,
}
export interface BeginnerPortfolioProject {
  'title' : string,
  'objective' : string,
  'strategy' : string,
  'execution' : string,
  'outcome' : string,
}
export interface BeginnerPortfolioSkill {
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface BeginnerPortfolioTool { 'icon' : string, 'name' : string }
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface CaseStudy {
  'id' : bigint,
  'title' : string,
  'serviceCategory' : string,
  'projectType' : string,
  'description' : string,
  'results' : string,
}
export interface Certification {
  'title' : string,
  'institution' : string,
  'year' : bigint,
}
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FAQ {
  'id' : bigint,
  'question' : string,
  'createdAt' : bigint,
  'answer' : string,
  'updatedAt' : bigint,
  'isVisible' : boolean,
  'category' : string,
  '_private' : boolean,
}
export interface MediaAsset {
  'id' : bigint,
  'file' : ExternalBlob,
  'type' : string,
  'description' : string,
}
export interface Phase {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'description' : string,
  'image' : string,
}
export interface Portfolio {
  'id' : bigint,
  'title' : string,
  'tools' : Array<Tool>,
  'focusArea' : string,
  'about' : string,
  'projects' : Array<Project>,
  'headline' : string,
  'caseStudies' : Array<CaseStudy>,
  'certifications' : Array<Certification>,
  'subheadline' : string,
  'skillsExperiences' : Array<SkillExperience>,
}
export interface PortfolioProject {
  'id' : bigint,
  'title' : string,
  'serviceCategory' : string,
  'projectType' : string,
  'description' : string,
  'results' : string,
  'image' : string,
}
export interface PricingGuideItem {
  'id' : bigint,
  'service' : string,
  'description' : string,
  'priceRange' : string,
  'skillLevel' : string,
}
export interface PricingGuideSection {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'pricingItems' : Array<PricingGuideItem>,
  'currency' : string,
}
export interface PricingGuideline {
  'id' : bigint,
  'title' : string,
  'takeaways' : Array<string>,
  'section' : PricingGuideSection,
  'realityCheckPoints' : Array<string>,
}
export interface PricingTier {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'price' : bigint,
  'recommendedForSmallBusiness' : boolean,
}
export interface Project {
  'title' : string,
  'objective' : string,
  'strategy' : string,
  'imageUrl' : string,
  'execution' : string,
  'outcome' : string,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'answersText' : string,
  'answers' : Array<string>,
  'isActive' : boolean,
  'correctAnswerIndex' : bigint,
  'roadmapSuggestion' : [] | [string],
  'recommendedTierId' : [] | [bigint],
}
export interface QuizResult {
  'id' : bigint,
  '_categoryAnalysis' : [] | [string],
  'tierRecommendation' : [] | [bigint],
  'score' : bigint,
  'roadmapPhaseRecommendation' : [] | [bigint],
}
export interface Resource {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'isFree' : boolean,
  'category' : string,
}
export interface Retrospective {
  'id' : bigint,
  'title' : string,
  'owner' : string,
  'reflections' : string,
  'timestamp' : bigint,
  'phase' : string,
}
export interface Section {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'resources' : Array<bigint>,
  'description' : string,
  'topics' : Array<string>,
  'phaseId' : bigint,
  'expanded' : boolean,
}
export interface SkillExperience {
  'application' : string,
  'skill' : string,
  'learningMethod' : string,
}
export interface Testimonial {
  'id' : bigint,
  'serviceCategory' : string,
  'clientName' : string,
  'quote' : string,
  'beforeAfter' : string,
  'resultMetrics' : string,
}
export interface Tool { 'name' : string, 'iconUrl' : string }
export interface Topic {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'completed' : boolean,
  'sectionId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogPost' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'addCaseStudy' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'addFAQ' : ActorMethod<[bigint, string, string, string], undefined>,
  'addMediaAsset' : ActorMethod<
    [bigint, ExternalBlob, string, string],
    undefined
  >,
  'addPhase' : ActorMethod<[bigint, string, string, string], undefined>,
  'addPortfolioProject' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
  'addPricingGuideline' : ActorMethod<
    [bigint, string, PricingGuideSection, Array<string>, Array<string>],
    undefined
  >,
  'addPricingTier' : ActorMethod<[bigint, string, Array<string>], undefined>,
  'addQuizQuestion' : ActorMethod<
    [
      bigint,
      string,
      Array<string>,
      bigint,
      string,
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
  'addResource' : ActorMethod<
    [bigint, string, string, boolean, string, string],
    undefined
  >,
  'addRetrospective' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'addSection' : ActorMethod<
    [bigint, bigint, string, string, Array<string>, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'addTopic' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'createBeginnerPortfolio' : ActorMethod<
    [
      bigint,
      string,
      string,
      BeginnerPortfolioHero,
      BeginnerPortfolioAbout,
      Array<BeginnerPortfolioSkill>,
      Array<BeginnerPortfolioProject>,
      [] | [BeginnerPortfolioCaseStudy],
      Array<BeginnerPortfolioTool>,
      Array<BeginnerPortfolioCertification>,
      BeginnerPortfolioContactCta,
    ],
    undefined
  >,
  'createPortfolio' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      Array<SkillExperience>,
      Array<Project>,
      Array<CaseStudy>,
      Array<Certification>,
      Array<Tool>,
    ],
    undefined
  >,
  'getAllBeginnerPortfolios' : ActorMethod<[], Array<BeginnerPortfolio>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPortfolioProjects' : ActorMethod<[], Array<PortfolioProject>>,
  'getAllPortfolios' : ActorMethod<[], Array<Portfolio>>,
  'getAllPricingGuidelinesForPricingPage' : ActorMethod<
    [],
    Array<PricingGuideline>
  >,
  'getAllPricingTiers' : ActorMethod<[], Array<PricingTier>>,
  'getAllQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getAllQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllSubscribers' : ActorMethod<[], Array<string>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBeginnerPortfolio' : ActorMethod<[bigint], [] | [BeginnerPortfolio]>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getFAQsByCategory' : ActorMethod<[string], Array<FAQ>>,
  'getMediaAssetsByType' : ActorMethod<[string], Array<MediaAsset>>,
  'getPhases' : ActorMethod<[], Array<Phase>>,
  'getPortfolio' : ActorMethod<[bigint], [] | [Portfolio]>,
  'getRandomImages' : ActorMethod<[bigint], Array<MediaAsset>>,
  'getRetrospectivesByOwner' : ActorMethod<[string], Array<Retrospective>>,
  'getRetrospectivesByPhase' : ActorMethod<[string], Array<Retrospective>>,
  'getSectionsByPhase' : ActorMethod<[bigint], Array<Section>>,
  'getTierPriceInRupees' : ActorMethod<[bigint], bigint>,
  'getTopicsBySection' : ActorMethod<[bigint], Array<Topic>>,
  'initializePricingTiers' : ActorMethod<[], undefined>,
  'saveQuizResult' : ActorMethod<
    [bigint, bigint, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'searchBlogPosts' : ActorMethod<[string], Array<BlogPost>>,
  'searchFAQs' : ActorMethod<[string], Array<FAQ>>,
  'submitContactForm' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePricingGuideSection' : ActorMethod<
    [bigint, PricingGuideSection],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];