/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PricingGuideItem = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Text,
  'skillLevel' : IDL.Text,
});
export const PricingGuideSection = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'pricingItems' : IDL.Vec(PricingGuideItem),
  'currency' : IDL.Text,
});
export const BeginnerPortfolioHero = IDL.Record({
  'headline' : IDL.Text,
  'ctaViewWork' : IDL.Text,
  'ctaContact' : IDL.Text,
  'subheadline' : IDL.Text,
});
export const BeginnerPortfolioAbout = IDL.Record({
  'bio' : IDL.Text,
  'focus' : IDL.Text,
});
export const BeginnerPortfolioSkill = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const BeginnerPortfolioProject = IDL.Record({
  'title' : IDL.Text,
  'objective' : IDL.Text,
  'strategy' : IDL.Text,
  'execution' : IDL.Text,
  'outcome' : IDL.Text,
});
export const BeginnerPortfolioCaseStudy = IDL.Record({
  'title' : IDL.Text,
  'research' : IDL.Text,
  'strategy' : IDL.Text,
  'learnings' : IDL.Text,
  'execution' : IDL.Text,
  'problem' : IDL.Text,
});
export const BeginnerPortfolioTool = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
});
export const BeginnerPortfolioCertification = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const BeginnerPortfolioContactCta = IDL.Record({
  'headline' : IDL.Text,
  'contactUrl' : IDL.Text,
  'ctaText' : IDL.Text,
});
export const SkillExperience = IDL.Record({
  'application' : IDL.Text,
  'skill' : IDL.Text,
  'learningMethod' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'objective' : IDL.Text,
  'strategy' : IDL.Text,
  'imageUrl' : IDL.Text,
  'execution' : IDL.Text,
  'outcome' : IDL.Text,
});
export const CaseStudy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'projectType' : IDL.Text,
  'description' : IDL.Text,
  'results' : IDL.Text,
});
export const Certification = IDL.Record({
  'title' : IDL.Text,
  'institution' : IDL.Text,
  'year' : IDL.Nat,
});
export const Tool = IDL.Record({ 'name' : IDL.Text, 'iconUrl' : IDL.Text });
export const BeginnerPortfolio = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tools' : IDL.Vec(BeginnerPortfolioTool),
  'about' : BeginnerPortfolioAbout,
  'projects' : IDL.Vec(BeginnerPortfolioProject),
  'hero' : BeginnerPortfolioHero,
  'contactCta' : BeginnerPortfolioContactCta,
  'introduction' : IDL.Text,
  '_caseStudy' : IDL.Opt(BeginnerPortfolioCaseStudy),
  'certifications' : IDL.Vec(BeginnerPortfolioCertification),
  'skills' : IDL.Vec(BeginnerPortfolioSkill),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PortfolioProject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'projectType' : IDL.Text,
  'description' : IDL.Text,
  'results' : IDL.Text,
  'image' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tools' : IDL.Vec(Tool),
  'focusArea' : IDL.Text,
  'about' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'headline' : IDL.Text,
  'caseStudies' : IDL.Vec(CaseStudy),
  'certifications' : IDL.Vec(Certification),
  'subheadline' : IDL.Text,
  'skillsExperiences' : IDL.Vec(SkillExperience),
});
export const PricingGuideline = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'takeaways' : IDL.Vec(IDL.Text),
  'section' : PricingGuideSection,
  'realityCheckPoints' : IDL.Vec(IDL.Text),
});
export const PricingTier = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'price' : IDL.Int,
  'recommendedForSmallBusiness' : IDL.Bool,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answersText' : IDL.Text,
  'answers' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'correctAnswerIndex' : IDL.Int,
  'roadmapSuggestion' : IDL.Opt(IDL.Text),
  'recommendedTierId' : IDL.Opt(IDL.Nat),
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  '_categoryAnalysis' : IDL.Opt(IDL.Text),
  'tierRecommendation' : IDL.Opt(IDL.Nat),
  'score' : IDL.Nat,
  'roadmapPhaseRecommendation' : IDL.Opt(IDL.Nat),
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'category' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'serviceCategory' : IDL.Text,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'beforeAfter' : IDL.Text,
  'resultMetrics' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'createdAt' : IDL.Int,
  'answer' : IDL.Text,
  'updatedAt' : IDL.Int,
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
  '_private' : IDL.Bool,
});
export const MediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'file' : ExternalBlob,
  'type' : IDL.Text,
  'description' : IDL.Text,
});
export const Phase = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'image' : IDL.Text,
});
export const Retrospective = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Text,
  'reflections' : IDL.Text,
  'timestamp' : IDL.Int,
  'phase' : IDL.Text,
});
export const Section = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'resources' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'phaseId' : IDL.Nat,
  'expanded' : IDL.Bool,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'completed' : IDL.Bool,
  'sectionId' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addCaseStudy' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addFAQ' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMediaAsset' : IDL.Func(
      [IDL.Nat, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPhase' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPortfolioProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPricingGuideline' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        PricingGuideSection,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addPricingTier' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addQuizQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Int,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addResource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addRetrospective' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addSection' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addTopic' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'createBeginnerPortfolio' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        BeginnerPortfolioHero,
        BeginnerPortfolioAbout,
        IDL.Vec(BeginnerPortfolioSkill),
        IDL.Vec(BeginnerPortfolioProject),
        IDL.Opt(BeginnerPortfolioCaseStudy),
        IDL.Vec(BeginnerPortfolioTool),
        IDL.Vec(BeginnerPortfolioCertification),
        BeginnerPortfolioContactCta,
      ],
      [],
      [],
    ),
  'createPortfolio' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SkillExperience),
        IDL.Vec(Project),
        IDL.Vec(CaseStudy),
        IDL.Vec(Certification),
        IDL.Vec(Tool),
      ],
      [],
      [],
    ),
  'getAllBeginnerPortfolios' : IDL.Func(
      [],
      [IDL.Vec(BeginnerPortfolio)],
      ['query'],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllPortfolioProjects' : IDL.Func(
      [],
      [IDL.Vec(PortfolioProject)],
      ['query'],
    ),
  'getAllPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
  'getAllPricingGuidelinesForPricingPage' : IDL.Func(
      [],
      [IDL.Vec(PricingGuideline)],
      ['query'],
    ),
  'getAllPricingTiers' : IDL.Func([], [IDL.Vec(PricingTier)], ['query']),
  'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getAllQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBeginnerPortfolio' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BeginnerPortfolio)],
      ['query'],
    ),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getFAQsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FAQ)], ['query']),
  'getMediaAssetsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MediaAsset)],
      ['query'],
    ),
  'getPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'getPortfolio' : IDL.Func([IDL.Nat], [IDL.Opt(Portfolio)], ['query']),
  'getRandomImages' : IDL.Func([IDL.Nat], [IDL.Vec(MediaAsset)], []),
  'getRetrospectivesByOwner' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Retrospective)],
      ['query'],
    ),
  'getRetrospectivesByPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Retrospective)],
      ['query'],
    ),
  'getSectionsByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Section)], ['query']),
  'getTierPriceInRupees' : IDL.Func([IDL.Nat], [IDL.Int], ['query']),
  'getTopicsBySection' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
  'initializePricingTiers' : IDL.Func([], [], []),
  'saveQuizResult' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'searchBlogPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'searchFAQs' : IDL.Func([IDL.Text], [IDL.Vec(FAQ)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePricingGuideSection' : IDL.Func(
      [IDL.Nat, PricingGuideSection],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PricingGuideItem = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Text,
    'skillLevel' : IDL.Text,
  });
  const PricingGuideSection = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'pricingItems' : IDL.Vec(PricingGuideItem),
    'currency' : IDL.Text,
  });
  const BeginnerPortfolioHero = IDL.Record({
    'headline' : IDL.Text,
    'ctaViewWork' : IDL.Text,
    'ctaContact' : IDL.Text,
    'subheadline' : IDL.Text,
  });
  const BeginnerPortfolioAbout = IDL.Record({
    'bio' : IDL.Text,
    'focus' : IDL.Text,
  });
  const BeginnerPortfolioSkill = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const BeginnerPortfolioProject = IDL.Record({
    'title' : IDL.Text,
    'objective' : IDL.Text,
    'strategy' : IDL.Text,
    'execution' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const BeginnerPortfolioCaseStudy = IDL.Record({
    'title' : IDL.Text,
    'research' : IDL.Text,
    'strategy' : IDL.Text,
    'learnings' : IDL.Text,
    'execution' : IDL.Text,
    'problem' : IDL.Text,
  });
  const BeginnerPortfolioTool = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
  });
  const BeginnerPortfolioCertification = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
  });
  const BeginnerPortfolioContactCta = IDL.Record({
    'headline' : IDL.Text,
    'contactUrl' : IDL.Text,
    'ctaText' : IDL.Text,
  });
  const SkillExperience = IDL.Record({
    'application' : IDL.Text,
    'skill' : IDL.Text,
    'learningMethod' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'objective' : IDL.Text,
    'strategy' : IDL.Text,
    'imageUrl' : IDL.Text,
    'execution' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const CaseStudy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'projectType' : IDL.Text,
    'description' : IDL.Text,
    'results' : IDL.Text,
  });
  const Certification = IDL.Record({
    'title' : IDL.Text,
    'institution' : IDL.Text,
    'year' : IDL.Nat,
  });
  const Tool = IDL.Record({ 'name' : IDL.Text, 'iconUrl' : IDL.Text });
  const BeginnerPortfolio = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tools' : IDL.Vec(BeginnerPortfolioTool),
    'about' : BeginnerPortfolioAbout,
    'projects' : IDL.Vec(BeginnerPortfolioProject),
    'hero' : BeginnerPortfolioHero,
    'contactCta' : BeginnerPortfolioContactCta,
    'introduction' : IDL.Text,
    '_caseStudy' : IDL.Opt(BeginnerPortfolioCaseStudy),
    'certifications' : IDL.Vec(BeginnerPortfolioCertification),
    'skills' : IDL.Vec(BeginnerPortfolioSkill),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PortfolioProject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'projectType' : IDL.Text,
    'description' : IDL.Text,
    'results' : IDL.Text,
    'image' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tools' : IDL.Vec(Tool),
    'focusArea' : IDL.Text,
    'about' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'headline' : IDL.Text,
    'caseStudies' : IDL.Vec(CaseStudy),
    'certifications' : IDL.Vec(Certification),
    'subheadline' : IDL.Text,
    'skillsExperiences' : IDL.Vec(SkillExperience),
  });
  const PricingGuideline = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'takeaways' : IDL.Vec(IDL.Text),
    'section' : PricingGuideSection,
    'realityCheckPoints' : IDL.Vec(IDL.Text),
  });
  const PricingTier = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'price' : IDL.Int,
    'recommendedForSmallBusiness' : IDL.Bool,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answersText' : IDL.Text,
    'answers' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'correctAnswerIndex' : IDL.Int,
    'roadmapSuggestion' : IDL.Opt(IDL.Text),
    'recommendedTierId' : IDL.Opt(IDL.Nat),
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    '_categoryAnalysis' : IDL.Opt(IDL.Text),
    'tierRecommendation' : IDL.Opt(IDL.Nat),
    'score' : IDL.Nat,
    'roadmapPhaseRecommendation' : IDL.Opt(IDL.Nat),
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'serviceCategory' : IDL.Text,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'beforeAfter' : IDL.Text,
    'resultMetrics' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'createdAt' : IDL.Int,
    'answer' : IDL.Text,
    'updatedAt' : IDL.Int,
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
    '_private' : IDL.Bool,
  });
  const MediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'file' : ExternalBlob,
    'type' : IDL.Text,
    'description' : IDL.Text,
  });
  const Phase = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'image' : IDL.Text,
  });
  const Retrospective = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Text,
    'reflections' : IDL.Text,
    'timestamp' : IDL.Int,
    'phase' : IDL.Text,
  });
  const Section = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'resources' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'phaseId' : IDL.Nat,
    'expanded' : IDL.Bool,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'completed' : IDL.Bool,
    'sectionId' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addCaseStudy' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addFAQ' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMediaAsset' : IDL.Func(
        [IDL.Nat, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPhase' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPortfolioProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPricingGuideline' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          PricingGuideSection,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addPricingTier' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addQuizQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Int,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addResource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addRetrospective' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addSection' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addTopic' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'createBeginnerPortfolio' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          BeginnerPortfolioHero,
          BeginnerPortfolioAbout,
          IDL.Vec(BeginnerPortfolioSkill),
          IDL.Vec(BeginnerPortfolioProject),
          IDL.Opt(BeginnerPortfolioCaseStudy),
          IDL.Vec(BeginnerPortfolioTool),
          IDL.Vec(BeginnerPortfolioCertification),
          BeginnerPortfolioContactCta,
        ],
        [],
        [],
      ),
    'createPortfolio' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SkillExperience),
          IDL.Vec(Project),
          IDL.Vec(CaseStudy),
          IDL.Vec(Certification),
          IDL.Vec(Tool),
        ],
        [],
        [],
      ),
    'getAllBeginnerPortfolios' : IDL.Func(
        [],
        [IDL.Vec(BeginnerPortfolio)],
        ['query'],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllPortfolioProjects' : IDL.Func(
        [],
        [IDL.Vec(PortfolioProject)],
        ['query'],
      ),
    'getAllPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
    'getAllPricingGuidelinesForPricingPage' : IDL.Func(
        [],
        [IDL.Vec(PricingGuideline)],
        ['query'],
      ),
    'getAllPricingTiers' : IDL.Func([], [IDL.Vec(PricingTier)], ['query']),
    'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getAllQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBeginnerPortfolio' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BeginnerPortfolio)],
        ['query'],
      ),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getFAQsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FAQ)], ['query']),
    'getMediaAssetsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaAsset)],
        ['query'],
      ),
    'getPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'getPortfolio' : IDL.Func([IDL.Nat], [IDL.Opt(Portfolio)], ['query']),
    'getRandomImages' : IDL.Func([IDL.Nat], [IDL.Vec(MediaAsset)], []),
    'getRetrospectivesByOwner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Retrospective)],
        ['query'],
      ),
    'getRetrospectivesByPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Retrospective)],
        ['query'],
      ),
    'getSectionsByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Section)], ['query']),
    'getTierPriceInRupees' : IDL.Func([IDL.Nat], [IDL.Int], ['query']),
    'getTopicsBySection' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
    'initializePricingTiers' : IDL.Func([], [], []),
    'saveQuizResult' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'searchBlogPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'searchFAQs' : IDL.Func([IDL.Text], [IDL.Vec(FAQ)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePricingGuideSection' : IDL.Func(
        [IDL.Nat, PricingGuideSection],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };