/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Testimonial {
    id: bigint;
    serviceCategory: string;
    clientName: string;
    quote: string;
    beforeAfter: string;
    resultMetrics: string;
}
export interface PricingTier {
    id: bigint;
    features: Array<string>;
    name: string;
    price: bigint;
    recommendedForSmallBusiness: boolean;
}
export interface FAQ {
    id: bigint;
    question: string;
    createdAt: bigint;
    answer: string;
    updatedAt: bigint;
    isVisible: boolean;
    category: string;
    _private: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PortfolioProject {
    id: bigint;
    title: string;
    serviceCategory: string;
    projectType: string;
    description: string;
    results: string;
    image: string;
}
export interface MediaAsset {
    id: bigint;
    file: ExternalBlob;
    type: string;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    id: bigint;
    question: string;
    answersText: string;
    answers: Array<string>;
    isActive: boolean;
    correctAnswerIndex: bigint;
    roadmapSuggestion?: string;
    recommendedTierId?: bigint;
}
export interface ContactSubmission {
    id: bigint;
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export interface BeginnerPortfolioTool {
    icon: string;
    name: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BeginnerPortfolioSkill {
    name: string;
    description: string;
    category: string;
}
export interface BeginnerPortfolioProject {
    title: string;
    objective: string;
    strategy: string;
    execution: string;
    outcome: string;
}
export interface SkillExperience {
    application: string;
    skill: string;
    learningMethod: string;
}
export interface Phase {
    id: bigint;
    title: string;
    completed: boolean;
    description: string;
    image: string;
}
export interface BeginnerPortfolioContactCta {
    headline: string;
    contactUrl: string;
    ctaText: string;
}
export interface BeginnerPortfolio {
    id: bigint;
    title: string;
    tools: Array<BeginnerPortfolioTool>;
    about: BeginnerPortfolioAbout;
    projects: Array<BeginnerPortfolioProject>;
    hero: BeginnerPortfolioHero;
    contactCta: BeginnerPortfolioContactCta;
    introduction: string;
    _caseStudy?: BeginnerPortfolioCaseStudy;
    certifications: Array<BeginnerPortfolioCertification>;
    skills: Array<BeginnerPortfolioSkill>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface BeginnerPortfolioHero {
    headline: string;
    ctaViewWork: string;
    ctaContact: string;
    subheadline: string;
}
export interface PricingGuideline {
    id: bigint;
    title: string;
    takeaways: Array<string>;
    section: PricingGuideSection;
    realityCheckPoints: Array<string>;
}
export interface Portfolio {
    id: bigint;
    title: string;
    tools: Array<Tool>;
    focusArea: string;
    about: string;
    projects: Array<Project>;
    headline: string;
    caseStudies: Array<CaseStudy>;
    certifications: Array<Certification>;
    subheadline: string;
    skillsExperiences: Array<SkillExperience>;
}
export interface BeginnerPortfolioCertification {
    url: string;
    title: string;
}
export interface BeginnerPortfolioCaseStudy {
    title: string;
    research: string;
    strategy: string;
    learnings: string;
    execution: string;
    problem: string;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    category: string;
}
export interface BeginnerPortfolioAbout {
    bio: string;
    focus: string;
}
export interface CaseStudy {
    id: bigint;
    title: string;
    serviceCategory: string;
    projectType: string;
    description: string;
    results: string;
}
export interface QuizResult {
    id: bigint;
    _categoryAnalysis?: string;
    tierRecommendation?: bigint;
    score: bigint;
    roadmapPhaseRecommendation?: bigint;
}
export interface PricingGuideItem {
    id: bigint;
    service: string;
    description: string;
    priceRange: string;
    skillLevel: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Certification {
    title: string;
    institution: string;
    year: bigint;
}
export interface PricingGuideSection {
    id: bigint;
    title: string;
    description: string;
    pricingItems: Array<PricingGuideItem>;
    currency: string;
}
export interface Topic {
    id: bigint;
    title: string;
    content: string;
    completed: boolean;
    sectionId: bigint;
}
export interface Resource {
    id: bigint;
    url: string;
    title: string;
    featured: boolean;
    description: string;
    isFree: boolean;
    category: string;
}
export interface Tool {
    name: string;
    iconUrl: string;
}
export interface Project {
    title: string;
    objective: string;
    strategy: string;
    imageUrl: string;
    execution: string;
    outcome: string;
}
export interface Section {
    id: bigint;
    title: string;
    content: string;
    resources: Array<bigint>;
    description: string;
    topics: Array<string>;
    phaseId: bigint;
    expanded: boolean;
}
export interface Retrospective {
    id: bigint;
    title: string;
    owner: string;
    reflections: string;
    timestamp: bigint;
    phase: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBlogPost(id: bigint, title: string, content: string, author: string, category: string): Promise<void>;
    addCaseStudy(id: bigint, title: string, description: string, results: string, serviceCategory: string, projectType: string): Promise<void>;
    addFAQ(id: bigint, question: string, answer: string, category: string): Promise<void>;
    addMediaAsset(id: bigint, file: ExternalBlob, description: string, type: string): Promise<void>;
    addPhase(id: bigint, title: string, description: string, image: string): Promise<void>;
    addPortfolioProject(id: bigint, title: string, description: string, results: string, serviceCategory: string, image: string, projectType: string): Promise<void>;
    addPricingGuideline(id: bigint, title: string, section: PricingGuideSection, takeaways: Array<string>, realityCheckPoints: Array<string>): Promise<void>;
    addPricingTier(id: bigint, name: string, features: Array<string>): Promise<void>;
    addQuizQuestion(id: bigint, question: string, answers: Array<string>, correctAnswerIndex: bigint, answersText: string, recommendedTierId: bigint | null, roadmapSuggestion: string | null): Promise<void>;
    addResource(id: bigint, title: string, url: string, isFree: boolean, description: string, category: string): Promise<void>;
    addRetrospective(id: bigint, title: string, reflections: string, phase: string, owner: string): Promise<void>;
    addSection(id: bigint, phaseId: bigint, title: string, description: string, topics: Array<string>, content: string): Promise<void>;
    addTestimonial(id: bigint, clientName: string, quote: string, resultMetrics: string, beforeAfter: string, serviceCategory: string): Promise<void>;
    addTopic(id: bigint, sectionId: bigint, title: string, content: string): Promise<void>;
    createBeginnerPortfolio(id: bigint, title: string, introduction: string, hero: BeginnerPortfolioHero, about: BeginnerPortfolioAbout, skills: Array<BeginnerPortfolioSkill>, projects: Array<BeginnerPortfolioProject>, caseStudy: BeginnerPortfolioCaseStudy | null, tools: Array<BeginnerPortfolioTool>, certifications: Array<BeginnerPortfolioCertification>, contactCta: BeginnerPortfolioContactCta): Promise<void>;
    createPortfolio(id: bigint, title: string, headline: string, subheadline: string, about: string, focusArea: string, skillsExperiences: Array<SkillExperience>, projects: Array<Project>, caseStudies: Array<CaseStudy>, certifications: Array<Certification>, tools: Array<Tool>): Promise<void>;
    getAllBeginnerPortfolios(): Promise<Array<BeginnerPortfolio>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllCaseStudies(): Promise<Array<CaseStudy>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllPortfolioProjects(): Promise<Array<PortfolioProject>>;
    getAllPortfolios(): Promise<Array<Portfolio>>;
    getAllPricingGuidelinesForPricingPage(): Promise<Array<PricingGuideline>>;
    getAllPricingTiers(): Promise<Array<PricingTier>>;
    getAllQuizQuestions(): Promise<Array<QuizQuestion>>;
    getAllQuizResults(): Promise<Array<QuizResult>>;
    getAllResources(): Promise<Array<Resource>>;
    getAllSubscribers(): Promise<Array<string>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getBeginnerPortfolio(id: bigint): Promise<BeginnerPortfolio | null>;
    getBlogPostsByCategory(category: string): Promise<Array<BlogPost>>;
    getFAQsByCategory(category: string): Promise<Array<FAQ>>;
    getMediaAssetsByType(type: string): Promise<Array<MediaAsset>>;
    getPhases(): Promise<Array<Phase>>;
    getPortfolio(id: bigint): Promise<Portfolio | null>;
    getRandomImages(count: bigint): Promise<Array<MediaAsset>>;
    getRetrospectivesByOwner(owner: string): Promise<Array<Retrospective>>;
    getRetrospectivesByPhase(phase: string): Promise<Array<Retrospective>>;
    getSectionsByPhase(phaseId: bigint): Promise<Array<Section>>;
    getTierPriceInRupees(tierId: bigint): Promise<bigint>;
    getTopicsBySection(sectionId: bigint): Promise<Array<Topic>>;
    initializePricingTiers(): Promise<void>;
    saveQuizResult(id: bigint, score: bigint, tierRecommendation: bigint | null, roadmapPhaseRecommendation: bigint | null): Promise<void>;
    searchBlogPosts(searchTerm: string): Promise<Array<BlogPost>>;
    searchFAQs(searchTerm: string): Promise<Array<FAQ>>;
    submitContactForm(id: bigint, name: string, email: string, subject: string, message: string): Promise<void>;
    subscribeToNewsletter(email: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePricingGuideSection(guidelineId: bigint, section: PricingGuideSection): Promise<void>;
}
import type { BeginnerPortfolio as _BeginnerPortfolio, BeginnerPortfolioAbout as _BeginnerPortfolioAbout, BeginnerPortfolioCaseStudy as _BeginnerPortfolioCaseStudy, BeginnerPortfolioCertification as _BeginnerPortfolioCertification, BeginnerPortfolioContactCta as _BeginnerPortfolioContactCta, BeginnerPortfolioHero as _BeginnerPortfolioHero, BeginnerPortfolioProject as _BeginnerPortfolioProject, BeginnerPortfolioSkill as _BeginnerPortfolioSkill, BeginnerPortfolioTool as _BeginnerPortfolioTool, ExternalBlob as _ExternalBlob, MediaAsset as _MediaAsset, Portfolio as _Portfolio, QuizQuestion as _QuizQuestion, QuizResult as _QuizResult, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addCaseStudy(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCaseStudy(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCaseStudy(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addFAQ(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMediaAsset(arg0: bigint, arg1: ExternalBlob, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaAsset(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaAsset(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addPhase(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhase(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhase(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPortfolioProject(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addPricingGuideline(arg0: bigint, arg1: string, arg2: PricingGuideSection, arg3: Array<string>, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPricingGuideline(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPricingGuideline(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPricingTier(arg0: bigint, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPricingTier(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPricingTier(arg0, arg1, arg2);
            return result;
        }
    }
    async addQuizQuestion(arg0: bigint, arg1: string, arg2: Array<string>, arg3: bigint, arg4: string, arg5: bigint | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuizQuestion(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuizQuestion(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addResource(arg0: bigint, arg1: string, arg2: string, arg3: boolean, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addRetrospective(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetrospective(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetrospective(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addSection(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Array<string>, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSection(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSection(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addTestimonial(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addTopic(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopic(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopic(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createBeginnerPortfolio(arg0: bigint, arg1: string, arg2: string, arg3: BeginnerPortfolioHero, arg4: BeginnerPortfolioAbout, arg5: Array<BeginnerPortfolioSkill>, arg6: Array<BeginnerPortfolioProject>, arg7: BeginnerPortfolioCaseStudy | null, arg8: Array<BeginnerPortfolioTool>, arg9: Array<BeginnerPortfolioCertification>, arg10: BeginnerPortfolioContactCta): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBeginnerPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBeginnerPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
            return result;
        }
    }
    async createPortfolio(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<SkillExperience>, arg7: Array<Project>, arg8: Array<CaseStudy>, arg9: Array<Certification>, arg10: Array<Tool>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async getAllBeginnerPortfolios(): Promise<Array<BeginnerPortfolio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBeginnerPortfolios();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBeginnerPortfolios();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllCaseStudies(): Promise<Array<CaseStudy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCaseStudies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCaseStudies();
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllPortfolioProjects(): Promise<Array<PortfolioProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPortfolioProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPortfolioProjects();
            return result;
        }
    }
    async getAllPortfolios(): Promise<Array<Portfolio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPortfolios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPortfolios();
            return result;
        }
    }
    async getAllPricingGuidelinesForPricingPage(): Promise<Array<PricingGuideline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPricingGuidelinesForPricingPage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPricingGuidelinesForPricingPage();
            return result;
        }
    }
    async getAllPricingTiers(): Promise<Array<PricingTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPricingTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPricingTiers();
            return result;
        }
    }
    async getAllQuizQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizQuestions();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizQuestions();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuizResults(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizResults();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizResults();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return result;
        }
    }
    async getAllSubscribers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscribers();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getBeginnerPortfolio(arg0: bigint): Promise<BeginnerPortfolio | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBeginnerPortfolio(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBeginnerPortfolio(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByCategory(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByCategory(arg0);
            return result;
        }
    }
    async getFAQsByCategory(arg0: string): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQsByCategory(arg0);
            return result;
        }
    }
    async getMediaAssetsByType(arg0: string): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaAssetsByType(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaAssetsByType(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhases(): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhases();
            return result;
        }
    }
    async getPortfolio(arg0: bigint): Promise<Portfolio | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomImages(arg0: bigint): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomImages(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomImages(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetrospectivesByOwner(arg0: string): Promise<Array<Retrospective>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetrospectivesByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetrospectivesByOwner(arg0);
            return result;
        }
    }
    async getRetrospectivesByPhase(arg0: string): Promise<Array<Retrospective>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetrospectivesByPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetrospectivesByPhase(arg0);
            return result;
        }
    }
    async getSectionsByPhase(arg0: bigint): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionsByPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionsByPhase(arg0);
            return result;
        }
    }
    async getTierPriceInRupees(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierPriceInRupees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierPriceInRupees(arg0);
            return result;
        }
    }
    async getTopicsBySection(arg0: bigint): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicsBySection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicsBySection(arg0);
            return result;
        }
    }
    async initializePricingTiers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePricingTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePricingTiers();
            return result;
        }
    }
    async saveQuizResult(arg0: bigint, arg1: bigint, arg2: bigint | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async searchBlogPosts(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBlogPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBlogPosts(arg0);
            return result;
        }
    }
    async searchFAQs(arg0: string): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFAQs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFAQs(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async subscribeToNewsletter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToNewsletter(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePricingGuideSection(arg0: bigint, arg1: PricingGuideSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingGuideSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingGuideSection(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BeginnerPortfolio_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BeginnerPortfolio): BeginnerPortfolio {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MediaAsset_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaAsset): Promise<MediaAsset> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_QuizQuestion_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_QuizResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizResult): QuizResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BeginnerPortfolioCaseStudy]): BeginnerPortfolioCaseStudy | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BeginnerPortfolio]): BeginnerPortfolio | null {
    return value.length === 0 ? null : from_candid_BeginnerPortfolio_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Portfolio]): Portfolio | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tools: Array<_BeginnerPortfolioTool>;
    about: _BeginnerPortfolioAbout;
    projects: Array<_BeginnerPortfolioProject>;
    hero: _BeginnerPortfolioHero;
    contactCta: _BeginnerPortfolioContactCta;
    introduction: string;
    _caseStudy: [] | [_BeginnerPortfolioCaseStudy];
    certifications: Array<_BeginnerPortfolioCertification>;
    skills: Array<_BeginnerPortfolioSkill>;
}): {
    id: bigint;
    title: string;
    tools: Array<BeginnerPortfolioTool>;
    about: BeginnerPortfolioAbout;
    projects: Array<BeginnerPortfolioProject>;
    hero: BeginnerPortfolioHero;
    contactCta: BeginnerPortfolioContactCta;
    introduction: string;
    _caseStudy?: BeginnerPortfolioCaseStudy;
    certifications: Array<BeginnerPortfolioCertification>;
    skills: Array<BeginnerPortfolioSkill>;
} {
    return {
        id: value.id,
        title: value.title,
        tools: value.tools,
        about: value.about,
        projects: value.projects,
        hero: value.hero,
        contactCta: value.contactCta,
        introduction: value.introduction,
        _caseStudy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value._caseStudy)),
        certifications: value.certifications,
        skills: value.skills
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    question: string;
    answersText: string;
    answers: Array<string>;
    isActive: boolean;
    correctAnswerIndex: bigint;
    roadmapSuggestion: [] | [string];
    recommendedTierId: [] | [bigint];
}): {
    id: bigint;
    question: string;
    answersText: string;
    answers: Array<string>;
    isActive: boolean;
    correctAnswerIndex: bigint;
    roadmapSuggestion?: string;
    recommendedTierId?: bigint;
} {
    return {
        id: value.id,
        question: value.question,
        answersText: value.answersText,
        answers: value.answers,
        isActive: value.isActive,
        correctAnswerIndex: value.correctAnswerIndex,
        roadmapSuggestion: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.roadmapSuggestion)),
        recommendedTierId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.recommendedTierId))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    _categoryAnalysis: [] | [string];
    tierRecommendation: [] | [bigint];
    score: bigint;
    roadmapPhaseRecommendation: [] | [bigint];
}): {
    id: bigint;
    _categoryAnalysis?: string;
    tierRecommendation?: bigint;
    score: bigint;
    roadmapPhaseRecommendation?: bigint;
} {
    return {
        id: value.id,
        _categoryAnalysis: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value._categoryAnalysis)),
        tierRecommendation: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tierRecommendation)),
        score: value.score,
        roadmapPhaseRecommendation: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.roadmapPhaseRecommendation))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    file: _ExternalBlob;
    type: string;
    description: string;
}): Promise<{
    id: bigint;
    file: ExternalBlob;
    type: string;
    description: string;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.file),
        type: value.type,
        description: value.description
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BeginnerPortfolio>): Array<BeginnerPortfolio> {
    return value.map((x)=>from_candid_BeginnerPortfolio_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizResult>): Array<QuizResult> {
    return value.map((x)=>from_candid_QuizResult_n21(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaAsset>): Promise<Array<MediaAsset>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaAsset_n25(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BeginnerPortfolioCaseStudy | null): [] | [_BeginnerPortfolioCaseStudy] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
